// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package db

import (
	"context"
)

const getChoice = `-- name: GetChoice :one
SELECT id, fruits FROM choices WHERE id = $1
`

func (q *Queries) GetChoice(ctx context.Context, id int32) (Choice, error) {
	row := q.db.QueryRow(ctx, getChoice, id)
	var i Choice
	err := row.Scan(&i.ID, &i.Fruits)
	return i, err
}
